version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - "TZ=Japan"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./docker/mysql/.env
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      - "TZ=Japan"
    volumes:
      - ./html:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - db
